#!/usr/bin/env bash

awk '/^Container: container_/{g++} { print $0 > "container-"g }' "$@"

# Pass the logfile directly to output the container IDs as bellow 
#awk '/^Container: container_/{g++} { print $0 > "container-"g }' "text.txt"con
